unique_ids:
  forms: {GameCreator: ZWCILL42CKIVUOAQNNGCYOCYJLIN3KID, GameCreator.AddNewPlayer: IWAFKHQJI7XU3BVNHJFHDPEF23AOZ555}
  modules: {}
  server_modules: {ServerModule1: QKMDBRKTLUM3O57TJEGGNOJJKLCLCHS6}
  assets: {standard-page.html: XAIGNNH6KFVJJMBTFBMXNLXM6XXHKHBA, theme.css: UKXAAZKAWQXTW4W4XVPPAN7K3G7LHWKS}
